[ejs.landing]
updateAvailableTooltip = "Actualizacion disponible"
usernamePlaceholder = "Usuario"
usernameEditButton = "Editar"
settingsTooltip = "Configuración"
serverStatus = "SERVIDOR"
serverStatusPlaceholder = "OFFLINE"
mojangStatus = "MOJANG STATUS"
mojangStatusTooltipTitle = "Servicios"
mojangStatusNETitle = "Non&nbsp;Essential"
newsButton = "NOVEDADES"
launchButton = "JUGAR"
launchButtonPlaceholder = "&#8226; Ningun servidor seleccionado"
launchDetails = "Espera por favor.."
newsNavigationStatus = "{currentPage} of {totalPages}"
newsErrorLoadSpan = "Buscando noticias.."
newsErrorFailedSpan = "No se pudo cargar las novedades"
newsErrorRetryButton = "Intenta de nuevo"
newsErrorNoneSpan = "Sin novedades"

[ejs.login]
loginCancelText = "Cancelar"
loginSubheader = "LOGIN MINECRAFT"
loginEmailError = "* valor invalido"
loginEmailPlaceholder = "EMAIL O USUARIO"
loginPasswordError = "* Requerido"
loginPasswordPlaceholder = "CONTRASEÑA"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "olvidaste la contraseña?"
loginRememberMeText = "recordar cuenta?"
loginButtonText = "LOGEAR"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Necesitas una cuenta?"
loginPasswordDisclaimer1 = "Tu contrsaeña se envia directamente a Mojang, no se almacena."
loginPasswordDisclaimer2 = "{appName} no esta afiliado con Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Opciones de Login"
loginWithMicrosoft = "Login con Microsoft"
loginWithMojang = "Login con Mojang"
cancelButton = "Cancelar"

[ejs.overlay]
serverSelectHeader = "Servidores disponibles"
serverSelectConfirm = "Seleccionar"
serverSelectCancel = "Cancelar"
accountSelectHeader = "Selecciona una cuenta"
accountSelectConfirm = "Seleccionar"
accountSelectCancel = "Cancelar"

[ejs.settings]
navHeaderText = "Configuración"
navAccount = "Cuenta"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "About"
navUpdates = "Updates"
navDone = "Listo"
tabAccountHeaderText = "Configuración de cuenta"
tabAccountHeaderDesc = "Agrega o modifica cuentas."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Agregar cuenta Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Agregar cuenta Mojang"
minecraftTabHeaderText = "Opciones de Minecraft"
minecraftTabHeaderDesc = "Opciones de lanzamiento."
gameResolutionTitle = "Resolucion del juego"
launchFullscreenTitle = "Lanzar en pantalla completa."
autoConnectTitle = "Conectar al servidor automaticamente al iniciar."
launchDetachedTitle = "Iniciar proceso de juego separado del launcher."
launchDetachedDesc = "Si el juego no está separado, al cerrar el launcher también se cerrará el juego."
tabModsHeaderText = "Opciones de Mods"
tabModsHeaderDesc = "Activar o desactivar mods."
switchServerButton = "Cambiar"
requiredMods = "Mods Requeridos"
optionalMods = "Mods Opcionales"
dropinMods = "Mods adicionales"
addMods = "Agregar Mods"
dropinRefreshNote = "(F5 para actualizar)"
shaderpacks = "Shaderpacks"
shaderpackDesc = "Activar o desactivar shaders. Ten en cuenta que los shaders solo funcionarán sin problemas en equipos potentes. Puedes añadir paquetes personalizados aquí."
selectShaderpack = "Seleccionar Paquete de Shaders"
tabJavaHeaderText = "Ajustes de Java"
tabJavaHeaderDesc = "Gestionar la configuración de Java (avanzado)."
memoryTitle = "Memoria"
maxRAM = "RAM Máxima"
minRAM = "RAM Mínima"
memoryDesc = "La RAM mínima recomendada es de 3 gigabytes. Establecer los valores mínimo y máximo iguales puede reducir el lag."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Ejecutable de Java"
javaExecSelDialogTitle = "Seleccionar Ejecutable de Java"
javaExecSelButtonText = "Elegir Archivo"
javaExecDesc = "El ejecutable de Java se valida antes del lanzamiento del juego."
javaPathDesc = "La ruta debe terminar con <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Opciones JVM Adicionales"
jvmOptsDesc = "Opciones que se proporcionarán a la JVM en tiempo de ejecución. No se deben incluir <em>-Xms</em> y <em>-Xmx</em>."
launcherTabHeaderText = "Ajustes del Launcher"
launcherTabHeaderDesc = "Opciones relacionadas con el launcher en sí."
allowPrereleaseTitle = "Permitir Actualizaciones Preliminares."
allowPrereleaseDesc = "Las versiones preliminares incluyen nuevas características que pueden no haber sido completamente probadas o integradas.<br>Esto siempre será verdadero si estás usando una versión preliminar."
dataDirectoryTitle = "Directorio de Datos"
selectDataDirectory = "Seleccionar Directorio de Datos"
chooseFolder = "Elegir Carpeta"
dataDirectoryDesc = "Todos los archivos del juego y las instalaciones locales de Java se almacenarán en el directorio de datos.<br>Las capturas de pantalla y los guardados de mundos se almacenan en la carpeta de instancia para la configuración del servidor correspondiente."
aboutTabHeaderText = "Acerca de"
aboutTabHeaderDesc = "Ver información y notas de la versión actual."
aboutTitle = "{appName}"
stableRelease = "Versión Estable"
versionText = "Versión "
sourceGithub = "Código Fuente (GitHub)"
support = "Soporte"
devToolsConsole = "Consola de Herramientas de Desarrollo"
releaseNotes = "Notas de la Versión"
changelog = "Registro de Cambios"
noReleaseNotes = "No hay Notas de la Versión"
viewReleaseNotes = "Ver Notas de la Versión en GitHub"
launcherUpdatesHeaderText = "Actualizaciones del Launcher"
launcherUpdatesHeaderDesc = "Descargar, instalar y revisar actualizaciones para el launcher."
checkForUpdates = "Buscar Actualizaciones"
whatsNew = "Novedades"
updateReleaseNotes = "Notas de la Actualización"

[ejs.waiting]
waitingText = "Esperando a Microsoft.."

[ejs.welcome]
continueButton = "CONTINUAR"

[js.discord]
waiting = "Esperando al Cliente.."
state = "Servidor: {shortId}"

[js.index]
microsoftLoginTitle = "Inicio de Sesión de Microsoft"
microsoftLogoutTitle = "Cierre de Sesión de Microsoft"

[js.login]
login = "INICIAR SESIÓN"
loggingIn = "INICIANDO SESIÓN"
success = "ÉXITO"
tryAgain = "Intentar de Nuevo"

[js.login.error]
invalidValue = "* Valor Inválido"
requiredValue = "* Requerido"

[js.login.error.unknown]
title = "Error Desconocido Durante el Inicio de Sesión"
desc = "Ha ocurrido un error desconocido. Por favor, consulta la consola para más detalles."

[js.landing.launch]
pleaseWait = "Por favor, espera.."
failureTitle = "Error Durante el Lanzamiento"
failureText = "Consulta la consola (CTRL + Shift + i) para más detalles."
okay = "De acuerdo"

[js.landing.selectedAccount]
noAccountSelected = "Ninguna Cuenta Seleccionada"

[js.landing.selectedServer]
noSelection = "Ningún Servidor Seleccionado"
loading = "Cargando.."

[js.landing.serverStatus]
server = "SERVIDOR"
offline = "DESCONECTADO"
players = "JUGADORES"

[js.landing.systemScan]
checking = "Comprobando información del sistema.."
noCompatibleJava = "No se encontró una<br>Instalación de Java Compatible"
installJavaMessage = "Para lanzar Minecraft, necesitas una instalación de 64 bits de Java {major}. ¿Quieres que instalemos una copia?"
installJava = "Instalar Java"
installJavaManually = "Instalar Manualmente"
javaDownloadPrepare = "Preparando la Descarga de Java.."
javaDownloadFailureTitle = "Error Durante la Descarga de Java"
javaDownloadFailureText = "Consulta la consola (CTRL + Shift + i) para más detalles."
javaRequired = "Java es Necesario<br>para Lanzar"
javaRequiredMessage = 'Se requiere una instalación válida de Java {major} x64 para lanzar.<br><br>Por favor, consulta nuestra <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Guía de Gestión de Java</a> para instrucciones sobre cómo instalar Java manualmente.'
javaRequiredDismiss = "Entiendo"
javaRequiredCancel = "Volver"

[js.landing.downloadJava]
findJdkFailure = "No se pudo encontrar la distribución de OpenJDK."
javaDownloadCorruptedError = "El JDK descargado tiene un hash incorrecto, el archivo puede estar corrupto."
extractingJava = "Extrayendo Java"
javaInstalled = "¡Java Instalado!"

[js.landing.dlAsync]
loadingServerInfo = "Cargando información del servidor.."
fatalError = "Error Fatal"
unableToLoadDistributionIndex = "No se pudo cargar una copia del índice de distribución. Consulta la consola (CTRL + Shift + i) para más detalles."
pleaseWait = "Por favor, espera.."
errorDuringLaunchTitle = "Error Durante el Lanzamiento"
seeConsoleForDetails = "Consulta la consola (CTRL + Shift + i) para más detalles."
validatingFileIntegrity = "Validando integridad de archivos.."
errorDuringFileVerificationTitle = "Error Durante la Verificación de Archivos"
downloadingFiles = "Descargando archivos.."
errorDuringFileDownloadTitle = "Error Durante la Descarga de Archivos"
preparingToLaunch = "Preparándose para lanzar.."
launchingGame = "Lanzando juego.."
launchWrapperNotDownloaded = "The main file, LaunchWrapper, failed to download properly. As a result, the game cannot launch.<br><br>To fix this issue, temporarily turn off your antivirus software and launch the game again.<br><br>If you have time, please <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">submit an issue</a> and let us know what antivirus software you use. We'll contact them and try to straighten things out."
doneEnjoyServer = "¡Listo. Disfruta del servidor!"
checkConsoleForDetails = "Por favor, consulta la consola (CTRL + Shift + i) para más detalles."

[js.landing.news]
checking = "Buscando Noticias"

[js.landing.discord]
loading = "Cargando juego.."
joining = "¡Navegando hacia Poniente!"
joined = "¡Explorando el Reino!"

[js.overlay]
dismiss = "Descartar"

[js.settings.fileSelectors]
executables = "Ejecutables"
allFiles = "Todos los Archivos"

[js.settings.mstfLogin]
errorTitle = "Algo Salió Mal"
errorMessage = "La autenticación de Microsoft falló. Por favor, inténtalo de nuevo."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Algo Salió Mal"
errorMessage = "El cierre de sesión de Microsoft falló. Por favor, inténtalo de nuevo."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Seleccionar Cuenta"
selectedButton = "Cuenta Seleccionada ✔"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Advertencia<br>Esta es Tu Última Cuenta"
lastAccountWarningMessage = "Para usar el launcher, debes tener iniciada sesión en al menos una cuenta. Necesitarás iniciar sesión de nuevo después.<br><br>¿Estás seguro de que quieres cerrar sesión?"
confirmButton = "Estoy Seguro"
cancelButton = "Cancelar"

[js.settings.authAccountPopulate]
username = "Nombre de Usuario"
uuid = "UUID"
selectAccount = "Seleccionar Cuenta"
selectedAccount = "Cuenta Seleccionada ✓"
logout = "Cerrar Sesión"

[js.settings.dropinMods]
removeButton = "Eliminar"
deleteFailedTitle = "Fallo al Eliminar<br>Mod Drop-in {fullName}"
deleteFailedMessage = "Asegúrate de que el archivo no esté en uso e inténtalo de nuevo."
failedToggleTitle = "Fallo al Alternar<br>Uno o Más Mods Drop-in"
okButton = "De acuerdo"

[js.settings.serverListing]
mainServer = "Servidor Principal"

[js.settings.java]
selectedJava = "Seleccionado: Java {version} ({vendor})"
invalidSelection = "Selección Inválida"
requiresJava = "Requiere Java {major} x64."
availableOptions = "Opciones Disponibles para Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pre-lanzamiento"
stableReleaseTitle = "Versión Estable"
releaseNotesFailed = "Fallo al cargar las notas de la versión."

[js.settings.updates]
newReleaseTitle = "Nueva Versión Disponible"
newPreReleaseTitle = "Nuevo Pre-lanzamiento Disponible"
downloadingButton = "Descargando.."
downloadButton = 'Descargar de GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Cierra el launcher y ejecuta el dmg para actualizar.</span>'
latestVersionTitle = "Estás Ejecutando la Última Versión"
checkForUpdatesButton = "Buscar Actualizaciones"
checkingForUpdatesButton = "Buscando Actualizaciones.."

[js.settings.msftLogin]
errorTitle = "Fallo en el Inicio de Sesión de Microsoft"
errorMessage = "No pudimos autenticar tu cuenta de Microsoft. Por favor, inténtalo de nuevo."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Error Fatal: No se Pudo Cargar el Índice de Distribución"
fatalErrorMessage = "No se pudo establecer una conexión con nuestros servidores para descargar el índice de distribución. No había copias locales disponibles para cargar. <br><br>El índice de distribución es un archivo esencial que proporciona la información más reciente del servidor. El launcher no puede iniciar sin él. Asegúrate de estar conectado a internet y vuelve a lanzar la aplicación."
closeButton = "Cerrar"

[js.uibinder.validateAccount]
failedMessageTitle = "Fallo al Actualizar el Inicio de Sesión"
failedMessage = "No pudimos actualizar el inicio de sesión para <strong>{account}</strong>. Por favor, selecciona otra cuenta o inicia sesión de nuevo."
failedMessageSelectAnotherAccount = "No pudimos actualizar el inicio de sesión para <strong>{account}</strong>. Por favor, inicia sesión de nuevo."
loginButton = "Iniciar Sesión"
selectAnotherAccountButton = "Seleccionar Otra Cuenta"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Buscando Actualizaciones..."
installNowButton = "Instalar Ahora"
checkForUpdatesButton = "Buscar Actualizaciones"

[js.auth.microsoft.error]
noProfileTitle = "Error Durante el Inicio de Sesión:<br>Perfil No Configurado"
noProfileDesc = "Tu cuenta de Microsoft aún no tiene un perfil de Minecraft configurado. Si has comprado recientemente el juego o lo has canjeado a través de Xbox Game Pass, debes configurar tu perfil en <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>Si aún no has comprado el juego, también puedes hacerlo en <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Error Durante el Inicio de Sesión:<br>Sin Cuenta de Xbox"
noXboxAccountDesc = "Tu cuenta de Microsoft no tiene una cuenta de Xbox asociada."
xblBannedTitle = "Error Durante el Inicio de Sesión:<br>Xbox Live No Disponible"
xblBannedDesc = "Tu cuenta de Microsoft es de un país donde Xbox Live no está disponible o está prohibido."
under18Title = "Error Durante el Inicio de Sesión:<br>Se Requiere Aprobación Parental"
under18Desc = "Las cuentas de usuarios menores de 18 años deben ser añadidas a una Familia por un adulto."
unknownTitle = "Error Desconocido Durante el Inicio de Sesión"
unknownDesc = "Ha ocurrido un error desconocido. Por favor, consulta la consola para más detalles."

[js.auth.mojang.error]
methodNotAllowedTitle = "Error Interno:<br>Método No Permitido"
methodNotAllowedDesc = "Método no permitido. Por favor, reporta este error."
notFoundTitle = "Error Interno:<br>No Encontrado"
notFoundDesc = "No se encontró el punto de autenticación. Por favor, reporta este problema."
accountMigratedTitle = "Error Durante el Inicio de Sesión:<br>Cuenta Migrada"
accountMigratedDesc = "Has intentado iniciar sesión con una cuenta migrada. Intenta de nuevo usando el correo electrónico de la cuenta como nombre de usuario."
invalidCredentialsTitle = "Error Durante el Inicio de Sesión:<br>Credenciales Inválidas"
invalidCredentialsDesc = "El correo electrónico o la contraseña que has introducido son incorrectos. Por favor, inténtalo de nuevo."
tooManyAttemptsTitle = "Error Durante el Inicio de Sesión:<br>Demasiados Intentos"
tooManyAttemptsDesc = "Ha habido demasiados intentos de inicio de sesión con esta cuenta recientemente. Por favor, inténtalo de nuevo más tarde."
invalidTokenTitle = "Error Durante el Inicio de Sesión:<br>Token Inválido"
invalidTokenDesc = "El token de acceso proporcionado no es válido."
tokenHasProfileTitle = "Error Durante el Inicio de Sesión:<br>El Token Tiene un Perfil"
tokenHasProfileDesc = "El token de acceso ya tiene un perfil asignado. La selección de perfiles aún no está implementada."
credentialsMissingTitle = "Error Durante el Inicio de Sesión:<br>Faltan Credenciales"
credentialsMissingDesc = "No se envió el nombre de usuario/contraseña o la contraseña tiene menos de 3 caracteres."
invalidSaltVersionTitle = "Error Durante el Inicio de Sesión:<br>Versión de Salt Inválida"
invalidSaltVersionDesc = "Versión de salt inválida."
unsupportedMediaTypeTitle = "Error Interno:<br>Tipo de Medio No Soportado"
unsupportedMediaTypeDesc = "Tipo de medio no soportado. Por favor, reporta este error."
accountGoneTitle = "Error Durante el Inicio de Sesión:<br>Cuenta Migrada"
accountGoneDesc = "La cuenta ha sido migrada a una cuenta de Microsoft. Por favor, inicia sesión con Microsoft."
unreachableTitle = "Error Durante el Inicio de Sesión:<br>Inalcanzable"
unreachableDesc = "No se puede alcanzar los servidores de autenticación. Asegúrate de que estén en línea y que estés conectado a internet."
gameNotPurchasedTitle = "Error Durante el Inicio de Sesión:<br>Juego No Comprado"
gameNotPurchasedDesc = "La cuenta con la que estás intentando iniciar sesión no ha comprado una copia de Minecraft. Puedes comprar una copia en <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Error Desconocido Durante el Inicio de Sesión"
unknownErrorDesc = "Ha ocurrido un error desconocido. Por favor, consulta la consola para más detalles."